---
title: PGA Reach
timezone: UTC
collections:
  case_studies:
    title: Case Studies
    output: true
    permalink: "/case-studies/:categories/:title.html"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: case_studies
  values:
    layout: case-study
description: Impacting lives through golf.
copyright: "© 2017 The PGA of America. All rights reserved. PGA REACH is a trademark
  owned by the PGA of America"
email: fe_cr@hotmail.com
baseurl: ''
url: ''
google_analytics: 
plugins:
- jekyll-paginate
- jekyll-tidy
- jekyll-paginate-category
- jekyll-sitemap
- jekyll-feed
jekyll_tidy:
  compress_html: false
paginate: 5000
permalink: "/:categories/:title.html"
category_dir: "/"
category_layout: _templates/category.html
sass:
  style: expanded
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
excerpt_separator: "<!--more-->"
keep_files:
- ".git"
- ".svn"
img_path: "/assets/img/"
case_studies_path: case-studies/
css_path: "/assets/css/"
main_css: style.css
js_path: "/assets/js/"
main_js: main.js
jquery: false
jquery_url: https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js
bootstrap_url: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js
bootstrap_ie: https://maxcdn.bootstrapcdn.com/js/ie10-viewport-bug-workaround.js
modernizr: false
modernizr_url: http://yastatic.net/modernizr/2.7.1/modernizr.min.js
ie_version: false
grids: false
grids_url: http://grids.danieldipietro.com/assets/js/grids.js
include:
- _pages
