---
title: PGA Reach
timezone: UTC
collections:
  case_studies:
    title: Case Studies
    output: true
    permalink: "/case-studies/:categories/:title.html"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: case_studies
  values:
    layout: case-study
nav:
- text: Home
  url: "/"
- text: About
  url: "/about/"
- text: Blog
  url: "/blog/"
- text: Services
  url: "/#DataDiscovery"
- text: Case Studies
  url: "/#CaseStudies"
- text: Testimonials
  url: "/#Testimonials"
- text: Contact
  type: mailto
  class: MainHeader-item--contact
description: Impacting lives through golf.
copyright: "© 2017 The PGA of America. All rights reserved. PGA REACH is a trademark
  owned by the PGA of America"
email: fe_cr@hotmail.com
baseurl: ''
url: ''
google_analytics: 
plugins:
- jekyll-paginate
- jekyll-tidy
- jekyll-paginate-category
- jekyll-sitemap
- jekyll-feed
jekyll_tidy:
  compress_html: false
paginate: 5000
permalink: "/:categories/:title.html"
category_dir: "/"
category_layout: _templates/category.html
sass:
  style: expanded
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
excerpt_separator: "<!--more-->"
keep_files:
- ".git"
- ".svn"
include:
- _pages
