---
title: PGA Reach
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: case_studies
  values:
    layout: case-study
- scope:
    path: ''
    type: posts
  values:
    layout: post
    thumbnail-image:
navigation:
- item: Home
  url: "/"
- item: supporters
  url: "/supporters"
- item: PGA JR League
  url: "/services/youth/"
- item: PGA Hope
  url: "/services/military/"
- item: PGA Works
  url: "/services/diversity-inclusion/"
- item: Press & News
  url: "/press-and-news/"
slider:
- first-line: Impacting lives through
  second-line: golf
  image: "/uploads/slider3.jpg"
  donate-button: true
- first-line: Lorem ipsum dolor sit
  second-line: amet
  image: "/uploads/slider3.jpg"
  donate-button: false
intro-text: |-
  ### PGA REACH is the 501(c)(3) charitable foundation of the PGA of America.  The mission of PGA REACH is to positively impact the lives of youth, military, and diverse populations by enabling access to PGA Professionals, PGA Sections and the game of golf.
intro-video-url: https://vimeo.com/220053248
team:
- item: Ryan Cannon
  position: Senior Director
  image: "/uploads/Ryan-Cannon-Headshot-1.jpg"
- item: Davis Horton
  position: Director, Development and Strategy
  image: "/uploads/Davis-Horton-Headshot-1.jpg"
- item: Kelsey Conway
  position: Program Coordinator
  image: "/uploads/Kelsey-Headshot1-1.jpg"
- item: Rachel Mabee
  position: PGA WORKS Program Specialist
  image: "/uploads/rachel-headshot-e1510194576248.jpg"
- item: Chris Nowak
  position: Military & Veteran Liason
  image: "/uploads/Chris-Nowak-e1510194480619.jpg"
footer-first-column:
- item: Home
  url: "/"
- item: PGA JR LEAGUE
  url: https://pgareach.org/services/youth/
- item: PRESS & NEWS
  url: https://pgareach.org/category/press-and-news/
footer-second-column:
- item: SUPPORTERS
  url: https://pgareach.org/supporters/
- item: PGA HOPE
  url: https://pgareach.org/services/military/
- item: PGA WORKS
  url: https://pgareach.org/services/diversity-inclusion/
- item: ABOUT PGA OF AMERICA
  url: http://www.pga.com/pga-america
footer-third-column:
- title: DONATE
  text: Make your positive impact by donating to PGA REACH today
description: Impacting lives through golf.
brochure-asset: "/uploads/PGA-REACH-Brochure1.pdf"
copyright: "© 2017 The PGA of America. All rights reserved. PGA REACH is a trademark
  owned by the PGA of America"
email: fe_cr@hotmail.com
baseurl:
url:
google_analytics:
gems:
- jekyll-paginate
plugins_dir:
- jekyll-paginate
- jekyll-tidy
- jekyll-paginate-category
- jekyll-sitemap
- jekyll-feed
jekyll_tidy:
  compress_html: false
paginate: 10
paginate_path: "/press-and-news/page:num/"
sass:
  style: expanded
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
excerpt_separator: "<!--more-->"
keep_files:
- ".git"
- ".svn"
include:
- _pages
